"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8f^jh2+jj_i8c-$xdotl2i#@crsdoa9ohe_=pd2v=7j2td7p)k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'common.apps.CommonConfig',     # 로그인, 로그아웃은 전체 사이트에 공통기눙이기때문에 따로 생성
    'pybo.apps.PyboConfig',  # pybo앱을 설치앱 목록에 추가하여 테이블 생성 준비
    'django.contrib.admin',  # DB관련 필요한 앱 -> migrate필요
    'django.contrib.auth',  # 로그인, 로그아웃 관련 앱
    'django.contrib.contenttypes',  # DB관련 필요한 앱 -> migrate필요
    'django.contrib.sessions',  # DB관련 필요한 앱 -> migrate필요
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',  # tailwind 앱 추가
    'theme',    # tailwind-theme 테마 앱 추가
    'django_browser_reload',    # tailwind-django 프로젝트로 생성된 웹 페이지에 tailwindCSS를 적용하여 로딩해주는 앱 추가
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   # question_list.html 템플릿 파일 저장 경로
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', # DB 엔진명
        'NAME': BASE_DIR / 'db.sqlite3',    # DB 파일 저장 경로 및 파일명 - BASE_DIR : /Users/<사용자>/projects/mysite
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [    # STATICFILES_DIRS 라는 리스트 변수 추가
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

# 로그인 성공 후 이동하는 메인URL
LOGIN_REDIRECT_URL = '/'

# 로그아웃 시 이동하는 URL (default가 admin로그아웃 페이지기 때문에 변경해줘야 함)
LOGOUT_REDIRECT_URL = '/'

